modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/impleri/fluid-skills/issues"
license = "MIT"

[[mods]]
modId = "fluidskills"
version = "${version}"
displayName = "Fluid Skills"
authors = "impleri"
description = '''
A library mod that exposes KubeJS methods to restrict how players see and interact with fluids.
'''
#logoFile = ""

[[dependencies.fluidskills]]
modId = "playerskills"
mandatory = true
versionRange = "[1.7,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fluidskills]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fluidskills]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2]"
ordering = "NONE"
side = "BOTH"

[[dependencies.fluidskills]]
modId = "architectury"
mandatory = true
versionRange = "[6.2.43,)"
ordering = "AFTER"
side = "BOTH"
